"""
Backfill historical candles for your watchlist. Chunks requests to
respect Kite's per-request day limits, throttles to stay under Kite's
historical-data rate limit (~3 req/sec), retries on rate-limit errors,
and skips symbols already fully backfilled - safe to re-run/resume if
interrupted partway through a large (e.g. 500-symbol) run.

Requires watchlist_resolved.py (generated by instrument_lookup.py) to
exist first - run that before this.
"""
import sys
import time
from datetime import datetime, timedelta
from kite_auth import get_kite_client
from db import get_connection

try:
    from watchlist_resolved import WATCHLIST
except ImportError:
    print("watchlist_resolved.py not found. Run this first:")
    print("  python build_nifty500_symbols.py   # -> symbols.txt")
    print("  python instrument_lookup.py symbols.txt   # -> watchlist_resolved.py")
    sys.exit(1)

MAX_DAYS_PER_REQUEST = {
    "minute": 60, "3minute": 100, "5minute": 100,
    "10minute": 100, "15minute": 200, "30minute": 200,
    "60minute": 400, "day": 2000,
}
REQUEST_DELAY_SEC = 0.4  # ~2.5 req/sec, safely under Kite's ~3 req/sec cap


def seed_watchlist(conn):
    conn.executemany(
        "INSERT OR REPLACE INTO watchlist (symbol, instrument_token, exchange) VALUES (?, ?, ?)",
        [(w["symbol"], w["instrument_token"], w["exchange"]) for w in WATCHLIST],
    )
    conn.commit()


def _date_chunks(from_date: datetime, to_date: datetime, chunk_days: int):
    cursor = from_date
    while cursor < to_date:
        chunk_end = min(cursor + timedelta(days=chunk_days), to_date)
        yield cursor, chunk_end
        cursor = chunk_end


def _already_backfilled(conn, symbol: str, days_back: int) -> bool:
    """Skip symbols whose earliest stored candle already covers the
    requested range - makes re-running a large job resumable."""
    row = conn.execute("SELECT MIN(timestamp) as earliest FROM candles WHERE symbol = ?", (symbol,)).fetchone()
    if not row or not row["earliest"]:
        return False
    earliest = datetime.fromisoformat(row["earliest"].split("T")[0])
    target = datetime.now() - timedelta(days=days_back - 5)  # small tolerance
    return earliest <= target


def _fetch_with_retry(kite, instrument_token, chunk_start, chunk_end, interval, max_retries=3):
    for attempt in range(max_retries):
        try:
            return kite.historical_data(
                instrument_token=instrument_token, from_date=chunk_start,
                to_date=chunk_end, interval=interval,
            )
        except Exception as e:
            if "Too many requests" in str(e) or "429" in str(e):
                wait = 2 ** attempt * 2
                print(f"  Rate limited, backing off {wait}s...")
                time.sleep(wait)
            else:
                print(f"  Error fetching chunk: {e}")
                return []
    return []


def backfill_candles(kite, conn, days_back: int = 365, interval: str = "5minute", skip_existing: bool = True):
    to_date = datetime.now()
    from_date = to_date - timedelta(days=days_back)
    chunk_days = MAX_DAYS_PER_REQUEST.get(interval, 100) - 5

    total_symbols = len(WATCHLIST)
    for idx, w in enumerate(WATCHLIST, 1):
        if skip_existing and _already_backfilled(conn, w["symbol"], days_back):
            print(f"[{idx}/{total_symbols}] {w['symbol']}: already backfilled, skipping")
            continue

        total_rows = 0
        for chunk_start, chunk_end in _date_chunks(from_date, to_date, chunk_days):
            candles = _fetch_with_retry(kite, w["instrument_token"], chunk_start, chunk_end, interval)
            rows = [
                (w["symbol"], c["date"].isoformat(), c["open"], c["high"], c["low"], c["close"], c["volume"])
                for c in candles
            ]
            conn.executemany(
                "INSERT OR REPLACE INTO candles (symbol, timestamp, open, high, low, close, volume) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)", rows,
            )
            conn.commit()
            total_rows += len(rows)
            time.sleep(REQUEST_DELAY_SEC)

        print(f"[{idx}/{total_symbols}] {w['symbol']}: {total_rows} candles backfilled")


if __name__ == "__main__":
    conn = get_connection()
    seed_watchlist(conn)
    kite = get_kite_client()
    backfill_candles(kite, conn, days_back=365)
    conn.close()
