"""
Backfill historical candles for your watchlist. Chunks requests to
respect Kite's per-request day limits, throttles to stay under Kite's
historical-data rate limit (~3 req/sec), retries on rate-limit errors,
and skips symbols already fully backfilled - safe to re-run/resume if
interrupted partway through a large (e.g. 500-symbol) run.

Default interval is MINUTE, matching what ingest/live_ticker.py writes. The
original 5-minute default left the candles table holding two different
intervals with nothing to tell them apart, so a 200-candle load meant 200
minutes during a live session and 200 x 5 minutes for history. Because of
that, a backfill REPLACES the window it covers - re-running with a different
interval over existing data would otherwise leave both bars for every
aligned minute.

    python -m ingest.fetch_historical                    # 60 days of minute bars
    python -m ingest.fetch_historical --days 120         # more minute history
    python -m ingest.fetch_historical --interval 5minute # the old behaviour

Requires ingest/watchlist_resolved.py (generated by
ingest.instrument_lookup) to exist first - run that before this.
"""
import sys
import time
from datetime import datetime, timedelta
from core.freshness import MINUTE_KEY_FMT, candle_timestamp
from ingest.kite_auth import get_kite_client
from storage.db import get_connection

try:
    from ingest.watchlist_resolved import WATCHLIST
except ImportError:
    print("watchlist_resolved.py not found. Run this first:")
    print("  python -m ingest.build_nifty500_symbols           # -> symbols.txt")
    print("  python -m ingest.instrument_lookup symbols.txt   # -> ingest/watchlist_resolved.py")
    sys.exit(1)

MAX_DAYS_PER_REQUEST = {
    "minute": 60, "3minute": 100, "5minute": 100,
    "10minute": 100, "15minute": 200, "30minute": 200,
    "60minute": 400, "day": 2000,
}
REQUEST_DELAY_SEC = 0.4  # ~2.5 req/sec, safely under Kite's ~3 req/sec cap

# Minute bars are the basis the live ticker writes, so the backfill uses them
# too. Mixing a 5-minute history with 1-minute live candles in the same table
# makes "the last 200 candles" mean 200 minutes in one case and 200 x 5
# minutes in the other, which silently changes ATR, RSI and ADX between the
# backtest and the live session.
DEFAULT_INTERVAL = "minute"

# A minute bar is ~1/5 the span of a 5-minute bar, so the useful lookback
# differs by orders of magnitude. A year of minute candles for a 500-symbol
# watchlist is ~45 million rows - far more than this SQLite file should be -
# while 60 days is ~11 million and still a year of 5-minute bars is ~9
# million. Override with --days when you genuinely need more.
DEFAULT_DAYS_BACK = {
    "minute": 60, "3minute": 120, "5minute": 365, "10minute": 365,
    "15minute": 365, "30minute": 365, "60minute": 500, "day": 2000,
}


def seed_watchlist(conn):
    conn.executemany(
        "INSERT OR REPLACE INTO watchlist (symbol, instrument_token, exchange) VALUES (?, ?, ?)",
        [(w["symbol"], w["instrument_token"], w["exchange"]) for w in WATCHLIST],
    )
    conn.commit()


def _date_chunks(from_date: datetime, to_date: datetime, chunk_days: int):
    cursor = from_date
    while cursor < to_date:
        chunk_end = min(cursor + timedelta(days=chunk_days), to_date)
        yield cursor, chunk_end
        cursor = chunk_end


def _already_backfilled(conn, symbol: str, interval: str, days_back: int) -> bool:
    """Skip symbols already completed for THIS interval - makes re-running a
    large job resumable.

    Reads backfill_state rather than MIN(timestamp) from candles, because the
    candles table has no interval column: a symbol with a year of 5-minute
    bars would satisfy an earliest-candle test for a 60-day minute backfill
    and get skipped forever, which is exactly how you end up with the live
    stream writing minute bars into a table whose history is a different
    interval.
    """
    row = _backfill_record(conn, symbol, interval)
    if not row or not row["completed_at"] or not row["earliest"]:
        return False
    earliest = datetime.fromisoformat(row["earliest"].split("T")[0])
    target = datetime.now() - timedelta(days=max(days_back - 5, 0))  # small tolerance
    return earliest <= target


def _backfill_record(conn, symbol: str, interval: str):
    return conn.execute(
        "SELECT * FROM backfill_state WHERE symbol = ? AND interval = ?", (symbol, interval)
    ).fetchone()


def _replace_chunk(conn, symbol: str, rows, chunk_start: datetime, chunk_end: datetime) -> None:
    """Write one chunk, replacing whatever already occupied that window.

    A plain INSERT OR REPLACE is not enough: it keys on the exact timestamp
    string, so re-running with --interval minute over an existing 5-minute
    history would leave both bars for every fifth minute and silently
    double-count those minutes in every indicator. Deleting the half-open
    window first - minute-prefix bounds, so legacy "+05:30" rows match too -
    makes a backfill the authoritative source for the range it covers.
    """
    conn.execute(
        "DELETE FROM candles WHERE symbol = ? AND timestamp >= ? AND timestamp < ?",
        (symbol, chunk_start.strftime(MINUTE_KEY_FMT), chunk_end.strftime(MINUTE_KEY_FMT)),
    )
    if rows:
        conn.executemany(
            "INSERT OR REPLACE INTO candles (symbol, timestamp, open, high, low, close, volume) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)", rows,
        )
    conn.commit()


def _record_backfill(conn, symbol: str, interval: str, earliest, latest, rows: int) -> None:
    conn.execute(
        "INSERT INTO backfill_state (symbol, interval, earliest, latest, rows_total, completed_at) "
        "VALUES (?, ?, ?, ?, ?, ?) "
        "ON CONFLICT(symbol, interval) DO UPDATE SET earliest = excluded.earliest, "
        "latest = excluded.latest, rows_total = excluded.rows_total, "
        "completed_at = excluded.completed_at",
        (symbol, interval, earliest, latest, rows, datetime.now().isoformat()),
    )
    conn.commit()


def _fetch_with_retry(kite, instrument_token, chunk_start, chunk_end, interval, max_retries=3):
    for attempt in range(max_retries):
        try:
            return kite.historical_data(
                instrument_token=instrument_token, from_date=chunk_start,
                to_date=chunk_end, interval=interval,
            )
        except Exception as e:
            if "Too many requests" in str(e) or "429" in str(e):
                wait = 2 ** attempt * 2
                print(f"  Rate limited, backing off {wait}s...")
                time.sleep(wait)
            else:
                print(f"  Error fetching chunk: {e}")
                return []
    return []


def backfill_candles(kite, conn, days_back: int | None = None, interval: str = DEFAULT_INTERVAL,
                     skip_existing: bool = True):
    if days_back is None:
        days_back = DEFAULT_DAYS_BACK.get(interval, 365)
    to_date = datetime.now()
    from_date = to_date - timedelta(days=days_back)
    chunk_days = MAX_DAYS_PER_REQUEST.get(interval, 100) - 5

    total_symbols = len(WATCHLIST)
    print(f"Backfilling {days_back} day(s) of {interval} candles for {total_symbols} symbols "
          f"({chunk_days}-day request chunks).")
    for idx, w in enumerate(WATCHLIST, 1):
        if skip_existing and _already_backfilled(conn, w["symbol"], interval, days_back):
            print(f"[{idx}/{total_symbols}] {w['symbol']}: already backfilled, skipping")
            continue

        total_rows = 0
        earliest = latest = None
        for chunk_start, chunk_end in _date_chunks(from_date, to_date, chunk_days):
            candles = _fetch_with_retry(kite, w["instrument_token"], chunk_start, chunk_end, interval)
            # candle_timestamp normalises Kite's tz-aware datetimes to the
            # naive IST form the live ticker writes. Storing
            # `c["date"].isoformat()` here is what produced "...+05:30" rows
            # that the live stream could not replace or match.
            rows = [
                (w["symbol"], candle_timestamp(c["date"]), c["open"], c["high"], c["low"], c["close"], c["volume"])
                for c in candles
            ]
            _replace_chunk(conn, w["symbol"], rows, chunk_start, chunk_end)
            total_rows += len(rows)
            if rows:
                # ISO timestamps sort lexicographically, so min/max is a string compare.
                first, last = rows[0][1], rows[-1][1]
                earliest = first if earliest is None else min(earliest, first)
                latest = last if latest is None else max(latest, last)
            time.sleep(REQUEST_DELAY_SEC)

        # Recorded only after the full range succeeded, so an interrupted run
        # resumes this symbol rather than being marked complete.
        _record_backfill(conn, w["symbol"], interval, earliest, latest, total_rows)
        print(f"[{idx}/{total_symbols}] {w['symbol']}: {total_rows} {interval} candles backfilled")


def _parse_args(argv: list) -> tuple:
    interval = DEFAULT_INTERVAL
    days_back = None
    if "--interval" in argv:
        i = argv.index("--interval")
        if len(argv) > i + 1:
            interval = argv[i + 1]
    if "--days" in argv:
        i = argv.index("--days")
        if len(argv) > i + 1:
            days_back = int(argv[i + 1])
    if interval not in MAX_DAYS_PER_REQUEST:
        raise SystemExit(f"Unknown interval {interval!r}. Valid: {', '.join(MAX_DAYS_PER_REQUEST)}")
    return interval, days_back


if __name__ == "__main__":
    interval, days_back = _parse_args(sys.argv[1:])
    if days_back is None:
        days_back = DEFAULT_DAYS_BACK[interval]
    print(f"Interval: {interval} (this is what ingest.live_ticker writes), lookback: {days_back} day(s).")
    if interval == "minute":
        print(f"NOTE: minute history is roughly 375 rows per symbol per trading day - "
              f"{days_back} day(s) x {len(WATCHLIST)} symbols is on the order of "
              f"{375 * days_back * len(WATCHLIST):,} rows. Raise --days only if you "
              f"actually need more minute history than that.")
    conn = get_connection()
    seed_watchlist(conn)
    kite = get_kite_client()
    backfill_candles(kite, conn, days_back=days_back, interval=interval)
    conn.close()
